### ISSUE TITLE
Proposal for a change to the application guide structure

### ISSUE THREAD

**Issue by rohan-deshpande** [atlassian/tangerine#41]
## Overview

So currently the App guide structure looks like this:

```
Theme/
  App/
    Topic/
      Components (atoms and molecules)/
      Apps (organisms)/
      Pages/
      Routing/
      Server/
      SSR/
```
I would like to propose a change to this in order to colocate concerns in a more logical and communication friendly manner.

## Proposal

I'd like to propose that the guide structure be

```
Theme/
  SPA/
    Topic/
      UI/
        Pages/
        Apps/
        Components/
      Routing/
      Server/
        SSR/
```

I feel that this structure makes things very clear and easy for our puny human brains to navigate and talk about.

## Any additional information

In terms of the Atomic Design linkage, I would place this in `Theme/SPA/Topic/UI/README.md` and use illustrations with mappings to our terminologies.

**Comment by nadiam84** [comment]
@rohan-deshpande What bothers me about grouping everything under SPA is that it create this assumption, that everything within is relevant for the SPA only, which is not true. All the apps/components structure is completely independent from the SPA, only Pages are tied to it.

**Comment by rohan-deshpande** [comment]
@nadiam84 hmm, but `Routing` and `SSR` are specific SPA topics right? The distinction between what we are terming as `Pages`, `Apps` and `Components` to me, really only makes sense in the context of an SPA. In another context, these could mean entirely different things. Apps is already a bit of a weird word because generally I would see an App as the root level of everything. 

So my argument is that the terms are given more meaning through the context of the SPA topic heading.

**Comment by nadiam84** [comment]
@rohan-deshpande yep, routing and ssr are SPA topics.

But apps and components is about how you build your code in general, whether it's SPA or not is up to developers. Most of them are just packages with components essentially, what would change for them if they are rendered not in the SPA, but somewhere outside of it?

**Comment by rohan-deshpande** [comment]
Ok makes sense. I would argue that the `UI` directory is portable then and you should still put apps and components under this even if the topic is not `SPA`.

I do think it makes sense for there to be an `SPA` topic though as it is a large area of concern that is prone to a lot of bike shedding.

**Comment by nadiam84** [comment]
Yep, agree on the need for the SPA. What about something like this:

```
Theme/
  General Architecture/
    Topic/
       Components/
       Apps/
  SPA/
    Topic/
      Pages/
      Routing/
      Server/
        SSR/
```

**Comment by rohan-deshpande** [comment]
Hmm I’m not so sure about that because it removes the collocation of UI concerns.

I think the distinction is important when speaking about architecture. It allows you to clearly isolate the discussion to specific layers which share commonality.

If we are talking about pages or components or apps, then we are talking about UI, and in turn, when speaking about UI we are talking about either interactive or stylistic DOM nodes. 

This is not the case when speaking about Routing or the Server, they are not things the user really “interacts” with. I guess you could make the argument that they interact with routing but it’s kind of like saying the mouse is a computer OS GUI. 

This is why I like the encapsulation of these things under the topic of UI.

**Comment by nadiam84** [comment]
Yep, see your point here. My only problem with it is categorising it under "SPA" theme. When we are talking about UI, it does not equal SPA in general. It might be implemented in SPA fashion, but might be not. Our guidelines should be generic enough to accommodate for those use cases.

I don't want to create an impression, that if you don't have the SPA in your product, you can't use the guides.

**Comment by rohan-deshpande** [comment]
I think we can easily solve this then! :D 

How about 

```
Theme/
  General Architecture/
    Topic/
       UI/
         Components/
         Apps/
  SPA/
    Topic/
      UI/
        Pages/
        Apps/
        Components/
      Routing/
      Server/
        SSR/
```

Best of both worlds?

**Comment by nadiam84** [comment]
Closing this issue for now, since we don't have anything in the SPA section yet, and I don't want to over-engineer it right now. The current structure of the general architecture is almost exactly like your proposal already :)
