### ISSUE TITLE
[Question] 'resentational' on UI-layer README

### ISSUE THREAD

**Issue by ifndefdeadmau5** [atlassian/tangerine#65]
## Overview

Just simple question
## Proposal

What's does the 'resentational container' mean? haven't heard of this term in any react patterns yet.

**Comment by nadiam84** [comment]
Hi @ifndefdeadmau5 

It's a typo, it was meant to be "presentational". Fixed it and updated with the link to the pattern, thank you for the signal!

**Comment by ifndefdeadmau5** [comment]
@nadiam84 Whoa, thanks for the quick fix
